name: CI

on: [ push, pull_request, workflow_dispatch ]

jobs:
  build:
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4


      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          iwr -uri https://download.docker.com/win/static/stable/x86_64/docker-28.1.1.zip -outfile docker-28.1.1.zip
